export const countryCodes = [
  { code: '+234', flag: '🇳🇬', country: 'Nigeria' },
  { code: '+233', flag: '🇬🇭', country: 'Ghana' },
  { code: '+254', flag: '🇰🇪', country: 'Kenya' },
  { code: '+27', flag: '🇿🇦', country: 'South Africa' },
];

// Position options that match backend enum - all 47 positions
export const positions = [
  { value: 'frontend developer', label: 'Frontend Developer' },
  { value: 'backend developer', label: 'Backend Developer' },
  { value: 'fullstack developer', label: 'Full Stack Developer' },
  { value: 'mobile developer', label: 'Mobile Developer' },
  { value: 'devops engineer', label: 'DevOps Engineer' },
  { value: 'data engineer', label: 'Data Engineer' },
  { value: 'security engineer', label: 'Security Engineer' },
  { value: 'ui/ux developer', label: 'UI/UX Developer' },
  { value: 'game developer', label: 'Game Developer' },
  { value: 'embedded systems engineer', label: 'Embedded Systems Engineer' },
  { value: 'blockchain developer', label: 'Blockchain Developer' },
  { value: 'cloud engineer', label: 'Cloud Engineer' },
  {
    value: 'site reliability engineer (sre)',
    label: 'Site Reliability Engineer (SRE)',
  },
  { value: 'qa engineer', label: 'QA Engineer' },
  { value: 'test automation engineer', label: 'Test Automation Engineer' },
  { value: 'performance engineer', label: 'Performance Engineer' },
  { value: 'data scientist', label: 'Data Scientist' },
  { value: 'data analyst', label: 'Data Analyst' },
  { value: 'machine learning engineer', label: 'Machine Learning Engineer' },
  { value: 'ai engineer', label: 'AI Engineer' },
  {
    value: 'business intelligence analyst',
    label: 'Business Intelligence Analyst',
  },
  { value: 'database administrator', label: 'Database Administrator' },
  { value: 'cloud architect', label: 'Cloud Architect' },
  { value: 'systems administrator', label: 'Systems Administrator' },
  { value: 'network engineer', label: 'Network Engineer' },
  { value: 'platform engineer', label: 'Platform Engineer' },
  { value: 'infrastructure engineer', label: 'Infrastructure Engineer' },
  { value: 'cybersecurity analyst', label: 'Cybersecurity Analyst' },
  { value: 'penetration tester', label: 'Penetration Tester' },
  { value: 'security architect', label: 'Security Architect' },
  { value: 'product manager', label: 'Product Manager' },
  { value: 'technical product manager', label: 'Technical Product Manager' },
  { value: 'ui designer', label: 'UI Designer' },
  { value: 'ux designer', label: 'UX Designer' },
  { value: 'product designer', label: 'Product Designer' },
  { value: 'engineering manager', label: 'Engineering Manager' },
  { value: 'technical lead', label: 'Technical Lead' },
  { value: 'software architect', label: 'Software Architect' },
  { value: 'cto', label: 'CTO' },
  { value: 'tech lead', label: 'Tech Lead' },
  { value: 'scrum master', label: 'Scrum Master' },
  { value: 'technical writer', label: 'Technical Writer' },
  { value: 'developer advocate', label: 'Developer Advocate' },
  { value: 'solutions architect', label: 'Solutions Architect' },
  { value: 'integration engineer', label: 'Integration Engineer' },
  { value: 'api developer', label: 'API Developer' },
  { value: 'microservices engineer', label: 'Microservices Engineer' },
  { value: 'other', label: 'Other' },
] as const;

// Legacy roles array for backward compatibility (maps to position values)
export const roles: string[] = positions.map((p) => p.value);

// All available skills - expanded to cover all positions
const allSkills: string[] = [
  // Frontend
  'React',
  'Vue.js',
  'Angular',
  'Next.js',
  'Nuxt.js',
  'Svelte',
  'JavaScript',
  'TypeScript',
  'HTML',
  'CSS',
  'SASS',
  'SCSS',
  'Tailwind CSS',
  'Bootstrap',
  'Material UI',
  'Figma',
  'Adobe XD',
  'Sketch',
  'Webpack',
  'Vite',
  // Backend
  'Node.js',
  'Express',
  'NestJS',
  'FastAPI',
  'Django',
  'Flask',
  'Spring Boot',
  'Laravel',
  'Ruby on Rails',
  'ASP.NET',
  'GraphQL',
  'REST API',
  'gRPC',
  'Microservices',
  // Languages
  'Python',
  'Java',
  'C++',
  'C#',
  'Go',
  'Rust',
  'PHP',
  'Ruby',
  'Scala',
  'Kotlin',
  'Swift',
  'Dart',
  'Solidity',
  // Mobile
  'React Native',
  'Flutter',
  'Ionic',
  'Xamarin',
  // Databases
  'SQL',
  'MongoDB',
  'PostgreSQL',
  'MySQL',
  'Redis',
  'Elasticsearch',
  'Cassandra',
  'DynamoDB',
  'Firebase',
  'Supabase',
  // DevOps & Cloud
  'Docker',
  'Kubernetes',
  'Terraform',
  'Ansible',
  'Jenkins',
  'CI/CD',
  'GitLab CI',
  'GitHub Actions',
  'AWS',
  'Azure',
  'GCP',
  'DigitalOcean',
  'Heroku',
  'Vercel',
  'Netlify',
  // Data & AI
  'Machine Learning',
  'Deep Learning',
  'Data Science',
  'Data Analytics',
  'TensorFlow',
  'PyTorch',
  'Scikit-learn',
  'Pandas',
  'NumPy',
  'Jupyter',
  'Tableau',
  'Power BI',
  'Apache Spark',
  'Hadoop',
  // Blockchain
  'Web3',
  'Blockchain',
  'Smart Contracts',
  'Ethereum',
  'Solana',
  'IPFS',
  // Security
  'Cybersecurity',
  'Penetration Testing',
  'OWASP',
  'Security Auditing',
  // Testing
  'Jest',
  'Cypress',
  'Selenium',
  'Playwright',
  'Unit Testing',
  'Integration Testing',
  'E2E Testing',
  // Tools
  'Git',
  'GitHub',
  'GitLab',
  'Jira',
  'Confluence',
  'Slack',
  'Agile',
  'Scrum',
  'Kanban',
  // Networking & Infrastructure
  'Linux',
  'Unix',
  'Shell Scripting',
  'Bash',
  'Network Administration',
  'System Administration',
  // Design
  'UI Design',
  'UX Design',
  'User Research',
  'Prototyping',
  'Wireframing',
  // Management
  'Project Management',
  'Team Leadership',
  'Technical Writing',
  'Documentation',
];

// Position to skills mapping - comprehensive mapping for all 47 positions
const positionSkillsMap: Record<string, string[]> = {
  // Development Roles
  'frontend developer': [
    'React',
    'Vue.js',
    'Angular',
    'Next.js',
    'JavaScript',
    'TypeScript',
    'HTML',
    'CSS',
    'SASS',
    'Tailwind CSS',
    'Material UI',
    'Webpack',
    'Vite',
    'Git',
  ],
  'backend developer': [
    'Node.js',
    'Express',
    'NestJS',
    'Python',
    'Java',
    'Go',
    'Rust',
    'PHP',
    'SQL',
    'MongoDB',
    'PostgreSQL',
    'MySQL',
    'Redis',
    'GraphQL',
    'REST API',
    'Docker',
    'Git',
  ],
  'fullstack developer': [
    'React',
    'Node.js',
    'Express',
    'JavaScript',
    'TypeScript',
    'Python',
    'Java',
    'SQL',
    'MongoDB',
    'PostgreSQL',
    'MySQL',
    'Next.js',
    'Vue.js',
    'Angular',
    'GraphQL',
    'REST API',
    'HTML',
    'CSS',
    'Tailwind CSS',
    'Docker',
    'Git',
  ],
  'mobile developer': [
    'React Native',
    'Flutter',
    'Swift',
    'Kotlin',
    'Dart',
    'JavaScript',
    'TypeScript',
    'iOS',
    'Android',
    'Git',
  ],
  'ui/ux developer': [
    'Figma',
    'Adobe XD',
    'Sketch',
    'HTML',
    'CSS',
    'JavaScript',
    'React',
    'Vue.js',
    'UI Design',
    'UX Design',
    'User Research',
    'Prototyping',
    'Wireframing',
    'Git',
  ],
  'game developer': [
    'C++',
    'C#',
    'Unity',
    'Unreal Engine',
    'Python',
    'JavaScript',
    '3D Modeling',
    'Game Design',
    'Git',
  ],
  'embedded systems engineer': [
    'C',
    'C++',
    'Python',
    'Assembly',
    'Linux',
    'RTOS',
    'Microcontrollers',
    'Git',
  ],
  'blockchain developer': [
    'Solidity',
    'Web3',
    'Blockchain',
    'Smart Contracts',
    'Ethereum',
    'Solana',
    'JavaScript',
    'TypeScript',
    'Node.js',
    'IPFS',
    'Git',
  ],
  'cloud engineer': [
    'AWS',
    'Azure',
    'GCP',
    'Docker',
    'Kubernetes',
    'Terraform',
    'Python',
    'Linux',
    'CI/CD',
    'Git',
  ],
  'site reliability engineer (sre)': [
    'Kubernetes',
    'Docker',
    'AWS',
    'Azure',
    'GCP',
    'Terraform',
    'Ansible',
    'Python',
    'Go',
    'Linux',
    'Monitoring',
    'CI/CD',
    'Git',
  ],
  'qa engineer': [
    'Jest',
    'Cypress',
    'Selenium',
    'Playwright',
    'Unit Testing',
    'Integration Testing',
    'E2E Testing',
    'Python',
    'JavaScript',
    'Git',
  ],
  'test automation engineer': [
    'Selenium',
    'Cypress',
    'Playwright',
    'Jest',
    'Python',
    'Java',
    'JavaScript',
    'CI/CD',
    'Git',
  ],
  'performance engineer': [
    'Performance Testing',
    'Load Testing',
    'Python',
    'Java',
    'JavaScript',
    'APM Tools',
    'Monitoring',
    'Git',
  ],
  // Data & Analytics
  'data scientist': [
    'Python',
    'R',
    'Machine Learning',
    'Deep Learning',
    'Data Science',
    'TensorFlow',
    'PyTorch',
    'Scikit-learn',
    'Pandas',
    'NumPy',
    'Jupyter',
    'SQL',
    'Git',
  ],
  'data analyst': [
    'Python',
    'SQL',
    'Excel',
    'Tableau',
    'Power BI',
    'Data Analytics',
    'Pandas',
    'NumPy',
    'Jupyter',
    'Git',
  ],
  'machine learning engineer': [
    'Python',
    'Machine Learning',
    'Deep Learning',
    'TensorFlow',
    'PyTorch',
    'Scikit-learn',
    'Pandas',
    'NumPy',
    'SQL',
    'Docker',
    'Git',
  ],
  'ai engineer': [
    'Python',
    'Machine Learning',
    'Deep Learning',
    'TensorFlow',
    'PyTorch',
    'NLP',
    'Computer Vision',
    'SQL',
    'Docker',
    'Git',
  ],
  'business intelligence analyst': [
    'SQL',
    'Tableau',
    'Power BI',
    'Excel',
    'Python',
    'Data Analytics',
    'Data Visualization',
    'Git',
  ],
  'database administrator': [
    'SQL',
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Oracle',
    'Database Administration',
    'Backup & Recovery',
    'Performance Tuning',
    'Linux',
    'Git',
  ],
  // Infrastructure & Operations
  'cloud architect': [
    'AWS',
    'Azure',
    'GCP',
    'Terraform',
    'Kubernetes',
    'Docker',
    'Architecture Design',
    'System Design',
    'Linux',
    'Git',
  ],
  'systems administrator': [
    'Linux',
    'Unix',
    'Windows Server',
    'Shell Scripting',
    'Bash',
    'System Administration',
    'Network Administration',
    'Docker',
    'Git',
  ],
  'network engineer': [
    'Network Administration',
    'Cisco',
    'Routing',
    'Switching',
    'Firewall',
    'Linux',
    'Python',
    'Git',
  ],
  'platform engineer': [
    'Kubernetes',
    'Docker',
    'Terraform',
    'AWS',
    'Azure',
    'GCP',
    'CI/CD',
    'Python',
    'Go',
    'Git',
  ],
  'infrastructure engineer': [
    'Terraform',
    'Ansible',
    'Kubernetes',
    'Docker',
    'AWS',
    'Azure',
    'GCP',
    'Linux',
    'CI/CD',
    'Git',
  ],
  // Security
  'security engineer': [
    'Cybersecurity',
    'Python',
    'JavaScript',
    'Docker',
    'Kubernetes',
    'AWS',
    'Azure',
    'GCP',
    'Security Auditing',
    'Git',
  ],
  'cybersecurity analyst': [
    'Cybersecurity',
    'Security Auditing',
    'Penetration Testing',
    'OWASP',
    'Python',
    'Linux',
    'Network Security',
    'Git',
  ],
  'penetration tester': [
    'Penetration Testing',
    'Cybersecurity',
    'OWASP',
    'Kali Linux',
    'Python',
    'Network Security',
    'Git',
  ],
  'security architect': [
    'Security Architecture',
    'Cybersecurity',
    'AWS',
    'Azure',
    'GCP',
    'System Design',
    'Python',
    'Git',
  ],
  // Product & Design
  'product manager': [
    'Product Management',
    'Agile',
    'Scrum',
    'Jira',
    'User Research',
    'Analytics',
    'Git',
  ],
  'technical product manager': [
    'Product Management',
    'Technical Writing',
    'System Design',
    'Agile',
    'Scrum',
    'Python',
    'SQL',
    'Git',
  ],
  'ui designer': [
    'Figma',
    'Adobe XD',
    'Sketch',
    'UI Design',
    'Prototyping',
    'Wireframing',
    'HTML',
    'CSS',
    'Git',
  ],
  'ux designer': [
    'Figma',
    'Adobe XD',
    'Sketch',
    'UX Design',
    'User Research',
    'Prototyping',
    'Wireframing',
    'Analytics',
    'Git',
  ],
  'product designer': [
    'Figma',
    'Adobe XD',
    'Sketch',
    'UI Design',
    'UX Design',
    'User Research',
    'Prototyping',
    'Wireframing',
    'Git',
  ],
  // Management & Leadership
  'engineering manager': [
    'Team Leadership',
    'Project Management',
    'Agile',
    'Scrum',
    'Technical Writing',
    'System Design',
    'Git',
  ],
  'technical lead': [
    'Team Leadership',
    'System Design',
    'Architecture Design',
    'Code Review',
    'Agile',
    'Scrum',
    'Git',
  ],
  'software architect': [
    'System Design',
    'Architecture Design',
    'Microservices',
    'AWS',
    'Azure',
    'GCP',
    'Kubernetes',
    'Docker',
    'Git',
  ],
  cto: [
    'Strategic Planning',
    'Team Leadership',
    'System Design',
    'Architecture Design',
    'Business Strategy',
    'Git',
  ],
  'tech lead': [
    'Team Leadership',
    'System Design',
    'Code Review',
    'Technical Writing',
    'Agile',
    'Scrum',
    'Git',
  ],
  // Specialized
  'scrum master': [
    'Agile',
    'Scrum',
    'Kanban',
    'Jira',
    'Project Management',
    'Team Leadership',
    'Git',
  ],
  'technical writer': [
    'Technical Writing',
    'Documentation',
    'Markdown',
    'Git',
    'API Documentation',
  ],
  'developer advocate': [
    'Technical Writing',
    'Public Speaking',
    'Content Creation',
    'Community Management',
    'Git',
    'Documentation',
  ],
  'solutions architect': [
    'System Design',
    'Architecture Design',
    'AWS',
    'Azure',
    'GCP',
    'Microservices',
    'Git',
  ],
  'integration engineer': [
    'API Integration',
    'REST API',
    'GraphQL',
    'Python',
    'JavaScript',
    'Node.js',
    'Git',
  ],
  'api developer': [
    'REST API',
    'GraphQL',
    'Node.js',
    'Python',
    'Java',
    'Express',
    'FastAPI',
    'Git',
  ],
  'microservices engineer': [
    'Microservices',
    'Docker',
    'Kubernetes',
    'API Development',
    'Node.js',
    'Python',
    'Java',
    'Go',
    'Git',
  ],
  'data engineer': [
    'Python',
    'SQL',
    'MongoDB',
    'PostgreSQL',
    'MySQL',
    'Redis',
    'Apache Spark',
    'Hadoop',
    'Data Pipeline',
    'ETL',
    'Git',
  ],
  other: allSkills, // Show all skills for "other"
};

// Get skills filtered by selected positions
export const getSkillsForPositions = (
  selectedPositions: string[]
): string[] => {
  if (selectedPositions.length === 0) {
    return allSkills; // Show all skills if no position selected
  }

  // If "other" is selected, show all skills
  if (selectedPositions.includes('other')) {
    return allSkills;
  }

  // Collect unique skills from all selected positions
  const skillSet = new Set<string>();
  selectedPositions.forEach((position) => {
    const skills = positionSkillsMap[position] || [];
    skills.forEach((skill) => skillSet.add(skill));
  });

  // Convert to array and sort
  return Array.from(skillSet).sort();
};

// Export all skills for backward compatibility
export const skills: string[] = allSkills;

// Helper function to get position label from value
export const getPositionLabel = (value: string): string => {
  const position = positions.find((p) => p.value === value);
  return position?.label || value;
};

// Helper function to validate position value
export const isValidPosition = (value: string): boolean => {
  return positions.some((p) => p.value === value);
};

// Experience levels that match backend enum: 'entry level' | 'mid level' | 'senior level'
export const experienceLevels = [
  { value: 'entry level', label: 'Entry Level' },
  { value: 'mid level', label: 'Mid Level' },
  { value: 'senior level', label: 'Senior Level' },
] as const;

// Helper function to get experience level label from value
export const getExperienceLevelLabel = (value: string): string => {
  const level = experienceLevels.find((l) => l.value === value);
  return level?.label || value;
};

// Helper function to validate experience level value
export const isValidExperienceLevel = (value: string): boolean => {
  return experienceLevels.some((l) => l.value === value);
};

// Helper function to convert roles array to positions array (backend now expects array)
export const rolesToPositions = (roles: string[]): string[] => {
  if (roles.length === 0) return [];
  // Return all valid positions from roles array
  return roles.filter((role) => isValidPosition(role));
};

// Legacy function for backward compatibility - returns first position
export const rolesToPosition = (roles: string[]): string | undefined => {
  const positions = rolesToPositions(roles);
  return positions.length > 0 ? positions[0] : undefined;
};
